### PR TITLE
fix/equal-no-longer-exported

### PR DESCRIPTION
**Pull request by bulldog98**
Update jest-marbles to work with latest expect (^27.0.0)

### CODE REVIEW

**Comment by bulldog98** [comment]
this fixes #401

**Comment by Blafasel3** [comment]
Any updates on this?

**Comment by cedricduffournet** [comment]
Hello @justjeb, do you have time to check this PR ? as explain here https://github.com/just-jeb/jest-marbles/issues/401 this issue blocks our whole Angular 13 Update. Thanks

**Comment by just-jeb** [comment]
Proper fix here: #405

**Pull request closed without merging**
